from .random_sampling import RandomSampling
#from .ideal_ef_sampling import IdealEFSampling
from .leastconfidence import LeastConfidenceSampler
from .entropy import EntropySampler
from .margin import MarginSampler
from .badge import BadgeSampler
from .coreset import CoresetSampler
#from .variety_sampling import SwitchSampling
from .patient_diverse_sampling import PatientDiverseSampler
from .patient_diverse_entropy import PatientDiverseEntropySampler
from .patient_diverse_entropy_macro import PatientDiverseEntropyMacroSampler
from .patient_diverse_margin import PatientDiverseMarginSampler
from .patient_diverse_leastconfidence import PatientDiverseLeastConfidenceSampler
from .patient_diverse_badge import PatientDiverseBadgeSampler
from .clinically_diverse_sampling import ClinicallyDiverseSampler
from .clinically_diverse_entropy import ClinicallyDiverseEntropySampler
from .clinically_diverse_badge import ClinicallyDiverseBadgeSampler


